### ISSUE TITLE
Doesn't send email to all members of group(s)

### ISSUE THREAD

**Issue by clarkac1** [aghstrategies/com.aghstrategies.activityemail#1]
We have set this extension up to send emails to 2 groups, that have a total of 47 members. 2 of whom have no email address so it should send 45 emails.  However only 25 are sent - in fact, the same 25 each time (we have run this for 3 days).  The 25 contacts are from both groups.  I can see nothing in the code that limits the number of emails to 25! Using Civi I can send an email to all 45 contacts, using immediate email not bulk email, so there is no problem with 'do not email' settings or similar.
We are using Civi 5.19.4 and Drupal 7.69.

**Comment by alifrumin** [comment]
Great catch @clarkac1! Thank you for bringing this issue to our attention. CiviCRM API 3 calls have a default limit of 25, I removed this limit from the relevant API call with this [commit](https://github.com/aghstrategies/com.aghstrategies.activityemail/commit/a9e2e835cd37c3439f2ada3cbfae5095bfd4653b). Please test the most recent version of master (which includes this commit) and let us know if you continue to have this issue.

**Comment by clarkac1** [comment]
Would it be better to leave a restriction at 50, as this is the maximum number of emails that can be sent 'immediately'?

**Comment by alifrumin** [comment]
Hmm, while some places in CiviCRM the amount of emails you can send immediately is limited to 50, I do not think that restriction applies to this extension. It looks to me like each each group member is emailed individually [here](https://github.com/aghstrategies/com.aghstrategies.activityemail/blob/master/activityemail.php#L163) and would be even if there were more than 50 in the group.

**Comment by clarkac1** [comment]
Interesting point, I assumed too much.  I'll install the updated version and let you know how it goes.  Thanks for your help with this very useful extension.

**Comment by clarkac1** [comment]
The updated version ran yesterday & emailed 45 contacts - so all good.  Many thanks!

**Comment by alifrumin** [comment]
Great! Thanks @clarkac1
